export DATA_PATH=data/train/split_1_M0_setting2.json
export CONV_TEMPLATE=llama-3-instruct
export OUTPUT_DIR=./saved_models/llama-31-8b_infinite_zhuque
export MODEL_PATH=saved_models/llama-31-8b_infinite
export GA=16
export DS_CONFIG=configs/zero2.json
export REPORT_TO="wandb"
export LR=5e-6
export TRAIN_BATCH_SIZE=4
export WARMUP_RATIO=1e-5
export EPOCH=3
bash scripts/train_sft.sh
